### ISSUE TITLE
tracker: Internationalization

### ISSUE THREAD

**Issue by a-man-called-q** [call-me-q/zikr#1]
> Warning: This issue is a tracker, each points must have their own issues and linked to this issue.

In order to make Internationalization works, we need to have few things.

- [ ] fonts for Arabic-styled and normal style. (#2)
- [ ] Able to change Locale from `SettingsPage.dart` (#4)
- [ ] get and save locale from `shared_preferences` (#3)
