### ISSUE TITLE
tracker: Add Settings Page

### ISSUE THREAD

**Issue by call-me-q** [call-me-q/zikr#5]
> Warning: This issue is a tracker, each points must have their own issues and linked to this issue.

We need to have a proper Settings page

- [x] Add Settings Page layout. (#7)
- [x] List all items on the page. (#11)
- [x] Implement all items on the page. (#11)

**Comment by call-me-q** [comment]
Done with #7 and #11
